site_name: Documentation du projet
nav:
 - UserManagement: 1_Presentation/AdminManagement/UserManagement.md
 - BookManagement: 1_Presentation/AdminManagement/BookManagement.md
 - Statistics: 1_Presentation/AdminManagement/Statistics.md
 - LoanManagement: 1_Presentation/AdminManagement/LoanManagement.md
 - PenalityManagement: 1_Presentation/AdminManagement/PenalityManagement.md
 - LoansModel: 3_Persistance/Repository/Loans/Model/LoansModel.md
 - BookModel: 3_Persistance/Repository/Books/Model/BookModel.md
 - UserModel: 3_Persistance/Repository/Users/Model/UserModel.md
 - PenalityModel: 3_Persistance/Repository/Penalities/Model/PenalityModel.md
 - BookModel: 2_Buisiness/DTO/BookModel.md
 - PenalityModel: 2_Buisiness/DTO/PenalityModel.md
 - LoansModel: 2_Buisiness/DTO/LoansModel.md
 - UserModel: 2_Buisiness/DTO/UserModel.md
 - StatisticQueries: 2_Buisiness/workflow/StatisticQueries.md
 - UsersQueries: 2_Buisiness/workflow/UsersQueries.md
 - LoanQueries: 2_Buisiness/workflow/LoanQueries.md
 - PenalitiesQueries: 2_Buisiness/workflow/PenalitiesQueries.md
 - BookQueries: 2_Buisiness/workflow/BookQueries.md
